export const ENERGY_STYLE = `[hidden]{display:none!important}.profile-panel{border:1px solid var(--line);padding:22px;margin:20px 0}.profile-panel h2{margin:0 0 10px}.profile-panel p{color:var(--muted);line-height:1.5}.profile-fields{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.profile-fields label{display:grid;gap:8px;font-size:14px}.profile-fields input,.profile-fields select{min-width:0;width:100%;padding:12px;background:#020806;border:1px solid var(--line);color:var(--text);font:14px monospace}.profile-panel button{padding:13px 18px;margin-top:18px;color:var(--acid);background:transparent;border:1px solid var(--acid);cursor:pointer}.energy-readings{display:flex;flex-wrap:wrap;gap:18px;margin:18px 0;color:var(--mint);font:14px monospace}.scenario-caption{display:block;margin:18px 0 10px}button:disabled{opacity:.5;cursor:default}@media(max-width:760px){.profile-fields{grid-template-columns:1fr}}`;

export const ENERGY_PANEL = `<section class="profile-panel"><h2>Simulation profile</h2><p>Choose the data generated for the selected Twin. Profile and parameters are saved for this Twin.</p><form id="profile-form"><div class="profile-fields"><label>Profile<select id="profile-select"><option value="machine">Industrial machine</option><option value="energy">Energy — solar and demand</option></select></label></div><div id="energy-fields" hidden><p>Synthetic demonstration data. The UTC simulation clock advances with each sample; it is separate from the publication time. This simplified model is not a production forecast.</p><div class="profile-fields"><label>PV capacity (kW)<input id="pv-capacity" type="number" min="0.1" max="10000" step="0.1" required></label><label>Base demand (kW)<input id="base-load" type="number" min="0" max="10000" step="0.1" required></label><label>Random seed<input id="energy-seed" type="number" min="0" max="4294967295" step="1" required></label><label>Start time (UTC)<input id="energy-start" type="datetime-local" step="1" required></label><label>Simulated seconds per sample<input id="energy-step" type="number" min="1" max="3600" step="1" required></label></div></div><button type="submit" id="apply-profile">APPLY PROFILE</button></form><p id="profile-note">Applying a profile restarts its scenario at normal. Energy replay starts at the configured time; the stream keeps its current paused or running state.</p><div id="energy-readings" class="energy-readings" aria-live="polite" hidden></div></section>`;

export const ENERGY_CONTROLS = `<small class="scenario-caption" id="energy-caption" hidden>ENERGY SCENARIO / SYNTHETIC DATA</small><section class="controls" id="energy-controls" hidden><button class="scenario" data-scenario="normal"><small>00 / daily cycle</small><strong>Day and night</strong><span>Solar production follows a clear-sky UTC cycle.</span></button><button class="scenario" data-scenario="cloudy"><small>01 / weather</small><strong>Cloud cover</strong><span>Variable clouds reduce photovoltaic production.</span></button><button class="scenario" data-scenario="demand-peak"><small>02 / demand</small><strong>Demand peak</strong><span>Double the normal consumption profile.</span></button><button class="scenario alarm" data-scenario="inverter-offline"><small>03 / equipment</small><strong>Inverter offline</strong><span>PV output falls to zero; the grid supplies demand.</span></button></section>`;

export const ENERGY_SCRIPT = `
const profileSelect=document.querySelector('#profile-select'), energyFields=document.querySelector('#energy-fields'), profileForm=document.querySelector('#profile-form');
const energyInputs={pvCapacityKw:document.querySelector('#pv-capacity'),baseLoadKw:document.querySelector('#base-load'),seed:document.querySelector('#energy-seed'),startAt:document.querySelector('#energy-start'),stepSeconds:document.querySelector('#energy-step')};
let profileTwin='',profileDirty=false;
function showEnergyFields(){energyFields.hidden=profileSelect.value!=='energy';Object.values(energyInputs).forEach(input=>input.disabled=energyFields.hidden)}
profileForm.oninput=()=>{profileDirty=true;showEnergyFields()};
profileForm.onsubmit=async event=>{event.preventDefault();const button=document.querySelector('#apply-profile');button.disabled=true;try{const body={action:'profile',profile:profileSelect.value};if(body.profile==='energy'){body.energy={};for(const [key,input] of Object.entries(energyInputs))body.energy[key]=key==='startAt'?new Date(input.value+'Z').toISOString():Number(input.value)}await command(body);profileDirty=false;await refresh()}catch(error){ids.message.textContent=error.message}finally{button.disabled=false}};
function renderEnergy(s){
 const active=s?.profile==='energy';
 if(profileTwin!==s?.twinId){profileTwin=s?.twinId;profileDirty=false}
 if(!profileDirty){profileSelect.value=s?.profile||'machine';const e=s?.energy||{pvCapacityKw:50,baseLoadKw:20,seed:42,startAt:'2026-06-21T06:00:00.000Z',stepSeconds:300};for(const [key,input] of Object.entries(energyInputs))input.value=key==='startAt'?e[key].slice(0,19):e[key];showEnergyFields()}
 document.querySelector('#controls').hidden=active;document.querySelector('#machine-caption').hidden=active;
 document.querySelector('#energy-controls').hidden=!active;document.querySelector('#energy-caption').hidden=!active;
 ids.mobility.disabled=active||!s;document.querySelector('#apply-profile').disabled=!s||s.twinId==='unknown';
 const readings=document.querySelector('#energy-readings');readings.hidden=!active;
 const sample=s?.lastSample;readings.replaceChildren();
 if(active){const labels=sample?['SIMULATED '+sample.simulation.simulatedAt,['PV',sample.measurements.pvPower],['DEMAND',sample.measurements.loadPower],['GRID (+ import / − export)',sample.measurements.gridPower]]:['Waiting for an energy sample'];for(const item of labels){const span=document.createElement('span');span.textContent=Array.isArray(item)?item[0]+' '+item[1].value+' '+item[1].unit:item;readings.append(span)}}
}
`;
