import { filePaths } from "../files/openapi.js";
import { devicePaths } from "../devices/openapi.js";
import { sharingPaths } from "../sharing/openapi.js";
export const openApiDocument = {
  openapi: "3.0.3",
  info: { title: "ObjectID Digital Twin Integration Server", version: "0.1.0", description: "Stateless on-premise integration and interoperability layer for ObjectID Digital Twins." },
  servers: [{ url: "/" }],
  components: {
    securitySchemes: {
      ApiKey: { type: "apiKey", in: "header", name: "x-api-key" },
      TwinReadSession: { type: "http", scheme: "bearer", description: "Opaque Twin-scoped DID session returned by shared/twins/{id}/verify. Not a tenant API key or JWT." },
      Bearer: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
      TwinScopeCreation: { type: "apiKey", in: "header", name: "x-twinscope-creation", description: "Trusted TwinScope backend assertion, audience dtis-twin-create, bound to body, plant/node scope and Idempotency-Key. Not a general API key." },
    },
    schemas: {
      Error: { type: "object", properties: { error: { type: "object", required: ["code", "message", "category"], properties: { code: { type: "string" }, message: { type: "string" }, category: { type: "string" }, details: { type: "object" } } } } },
    },
  },
  paths: {
    ...filePaths,
    ...devicePaths,
    ...sharingPaths,
    "/health": { get: { summary: "Liveness", responses: { "200": { description: "Alive" } } } },
    "/ready": { get: { summary: "ObjectID and required dependency readiness", responses: { "200": { description: "Ready" }, "503": { description: "Not ready" } } } },
    "/status.json": { get: { summary: "Sanitized public DTIS service status and aggregate metrics", responses: { "200": { description: "Public operations status" } } } },
    "/api/v1/twins/{id}": {
      get: { summary: "Get Twin", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Twin" } } },
      patch: { summary: "Update Twin name, description and mutable metadata (owner/steward policy enforced)", responses: { "200": { description: "Updated on-chain" }, "403": { description: "Twin policy denied" } } },
    },
    "/api/v1/capabilities": { get: { summary: "Discover Integration Server capabilities", responses: { "200": { description: "Capabilities" } } } },
    "/api/v1/subscription": { get: { summary: "Get the authenticated tenant's on-chain subscription plan, period and usage", responses: { "200": { description: "Tenant subscription accounting" }, "403": { description: "Tenant/subscription mismatch" }, "503": { description: "Subscription unavailable" } } } },
    "/api/v1/storage/retention/status": { get: { summary: "Inspect automatic managed-storage retention status", responses: { "200": { description: "Retention policy and last pruning run" } } } },
    "/api/v1/twins/{id}/realtime/status": { get: { summary: "Get realtime availability for a Twin", responses: { "200": { description: "Realtime status" } } } },
    "/api/v1/public/twins/{id}/realtime/status": { get: { summary: "Get sanitized realtime availability for an on-chain public Twin (no authentication)", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", pattern: "^0x[0-9a-fA-F]{64}$" } }], responses: { "200": { description: "Sanitized public realtime status" }, "404": { description: "Twin is absent, invalid or not public on-chain" } } } },
    "/api/v1/public/twins/{id}/realtime/latest": { get: { summary: "Get the latest payload when both Twin and operational-data visibility are public on-chain", responses: { "200": { description: "Public realtime event without connector or tenant details" }, "404": { description: "Public operational data is unavailable or not enabled" } } } },
    "/api/v1/public/twins/{id}/location/latest": { get: { summary: "Get the latest normalized position when public live-location access is enabled on-chain", responses: { "200": { description: "Public CRS84 position without telemetry or connector details" }, "404": { description: "Public live location is unavailable or not enabled" } } } },
    "/api/v1/public/twins/{id}/realtime/stream": { get: { summary: "Stream public operational data using SSE while the on-chain policy remains public", responses: { "200": { description: "Sanitized public SSE stream" }, "404": { description: "Public operational data is not enabled" } } } },
    "/api/v1/twins/{id}/realtime/latest": { get: { summary: "Get the latest mapped realtime event", responses: { "200": { description: "Realtime event" }, "404": { description: "No realtime data" } } } },
    "/api/v1/twins/{id}/location/latest": { get: { summary: "Get the latest normalized CRS84 position", responses: { "200": { description: "Latest live position" }, "404": { description: "No live position" } } } },
    "/api/v1/twins/{id}/realtime/stream": { get: { summary: "Stream mapped realtime events using SSE", responses: { "200": { description: "SSE stream" } } } },
    "/api/v1/twins/{id}/command-catalog": { get: { summary: "Get the policy-filtered command catalog", responses: { "200": { description: "Command catalog" }, "403": { description: "Twin policy denied" } } } },
    "/api/v1/twins/{id}/commands": {
      get: { summary: "List recent commands", responses: { "200": { description: "Command history" } } },
      post: { summary: "Authorize, persist and dispatch a catalog command", responses: { "202": { description: "Command dispatched" }, "403": { description: "Twin policy denied" }, "422": { description: "Invalid or unlisted command" } } },
    },
    "/api/v1/twins/{id}/commands/{commandId}": { get: { summary: "Get command status", responses: { "200": { description: "Command record" }, "404": { description: "Command not found" } } } },
    "/api/v1/dids/{did}/twins": { get: { summary: "List Twins associated with a DID", responses: { "200": { description: "Twin summaries and DID roles" } } } },
    "/api/v1/twins": { post: { summary: "Create a personal Twin with the authenticated owner's subscription", description: "Requires the subscription owner. DTIS creates/reuses a private owner-isolated personal plant when plantId is omitted; organizational tenantId is null. The owner subscription must be active with Twin capacity and credits.", parameters: [{ name: "Idempotency-Key", in: "header", schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object" } } } }, responses: { "201": { description: "Created, including twinId, plantId, ownerDid, requesterDid and tenantId" }, "402": { description: "Subscription inactive or exhausted" }, "403": { description: "Not the subscription or plant owner" } } } },
    "/api/plants/twins": { post: { summary: "Create a plant-owned Twin after delegated TwinScope AAA authorization", security: [{ TwinScopeCreation: [] }], parameters: [{ name: "Idempotency-Key", in: "header", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["plantId", "nodeId", "name"], properties: { plantId: { type: "string" }, nodeId: { type: "string" }, name: { type: "string" } } } } } }, responses: { "201": { description: "Created for the pinned plant owner's subscription; requester tracked separately" }, "401": { description: "Missing or invalid scoped assertion" }, "402": { description: "Plant owner subscription unavailable or exhausted" }, "403": { description: "Scope or owner mismatch" }, "404": { description: "Plant or node not present on this IS" }, "409": { description: "Node already bound or idempotency conflict" } } } },
    "/api/v1/twins/{id}/states": { post: { summary: "Publish Twin state (policy enforced)", responses: { "202": { description: "Submitted" }, "403": { description: "Twin policy denied" } } } },
    "/api/v1/twins/{id}/datasets": { post: { summary: "Register Twin dataset (policy enforced)", responses: { "202": { description: "Submitted" }, "403": { description: "Twin policy denied" } } } },
    "/api/v1/twins/{id}/models": { post: { summary: "Register Twin model (policy enforced)", responses: { "202": { description: "Submitted" }, "403": { description: "Twin policy denied" } } } },
    "/api/v1/twins/{id}/interfaces": { post: { summary: "Register Twin interface (policy enforced)", responses: { "202": { description: "Submitted" }, "403": { description: "Twin policy denied" } } } },
    "/api/v1/twins/{id}/events": { post: { summary: "Register business or maintenance event (policy enforced)", responses: { "202": { description: "Submitted" }, "403": { description: "Twin policy denied" } } } },
    "/api/v1/twins/{id}/thread": { get: { summary: "Get Digital Thread", responses: { "200": { description: "Events" } } } },
    "/api/v1/twins/{id}/thread/verify": { get: { summary: "Verify Digital Thread", responses: { "200": { description: "Verification" } } } },
    "/api/v1/twins/{id}/thread/verify/report": { get: { summary: "Export Digital Thread audit evidence", responses: { "200": { description: "Evidence report" } } } },
    "/api/v1/twins/{id}/evidence-bundles": { post: { summary: "Create one on-demand Dataset snapshot and its Digital Thread anchor", responses: { "201": { description: "Created Dataset reference" } } } },
    "/api/v1/twins/{id}/evidence-bundles/{datasetId}": { get: { summary: "Download the ZIP for one previously created Dataset snapshot", responses: { "200": { description: "ZIP evidence bundle" } } } },
    "/api/v1/twins/{id}/evidence-bundles/validate": { post: { summary: "Validate a locally hashed snapshot ZIP against its live IOTA Dataset object and Digital Thread event", responses: { "200": { description: "Evidence validation result" } } } },
    "/api/v1/twins/{id}/validate-profile": { post: { summary: "Validate a payload against a versioned ISO-alignment profile", responses: { "200": { description: "Validation result" } } } },
    "/api/v1/profiles/{profileId}/validate": { post: { summary: "Validate a payload without Twin context", responses: { "200": { description: "Validation result" }, "422": { description: "Profile is not validatable" } } } },
    "/api/v1/profiles": { get: { summary: "List versioned profiles", responses: { "200": { description: "Profiles" } } } },
    "/api/v1/twins/{id}/identifiers": { get: { summary: "Get identifiers", responses: { "200": { description: "Identifiers" } } } },
    "/api/v1/resolve/{scheme}/{value}": { get: { summary: "Resolve globally through the ObjectID indexer or use the bounded twinId fallback", parameters: [{ name: "twinId", in: "query", required: false, schema: { type: "string" } }], responses: { "200": { description: "Matches" }, "501": { description: "Indexer required" } } } },
    "/api/v1/resolve/{sourceScheme}/{value}/to/{targetScheme}": { get: { summary: "Resolve a cross-scheme mapping globally or within twinId", parameters: [{ name: "twinId", in: "query", required: false, schema: { type: "string" } }], responses: { "200": { description: "Resolution" }, "501": { description: "Indexer required" } } } },
    "/api/v1/twins/{id}/maturity/evaluate": { post: { summary: "Evaluate maturity profile", parameters: [{ name: "commit", in: "query", schema: { type: "boolean" } }], responses: { "200": { description: "Assessment" } } } },
    "/api/v1/twins/{id}/maturity/assessments": { post: { summary: "Create maturity assessment (policy enforced)", responses: { "202": { description: "Submitted" }, "403": { description: "Twin policy denied" } } } },
  },
} as const;
