const twin = { name: 'id', in: 'path', required: true, schema: { type: 'string', pattern: '^0x[0-9a-f]{64}$' } };
const job = { name: 'requestId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } };
const session = [{ TwinReadSession: [] }];
const errors = { '401': { description: 'DID session missing or expired' }, '403': { description: 'DID lacks the required on-chain scope, or access revoked' }, '404': { description: 'Request not found or expired' }, '429': { description: 'Request rate or export capacity exceeded' } };
const json = (schema: unknown) => ({ required: true, content: { 'application/json': { schema } } });
const didList = { type: 'array', maxItems: 100, items: { type: 'string' } };
const measurements = { type: 'array', minItems: 1, maxItems: 64, uniqueItems: true, items: { type: 'string', pattern: '^[A-Za-z][A-Za-z0-9_]{0,63}$' }, description: 'Optional exact keys, a subset of the authorized measures. Omit for all authorized measures. constructor and prototype are not allowed.' };
export const sharingPaths = {
  '/.well-known/objectid-dataset-keys.json': { get: { summary: 'Public Integration Server Ed25519 dataset signing identity; obtain approval independently before trusting it', security: [], responses: { '200': { description: 'objectid.dataset-signers.v1: issuer, network, keyId (SHA256 SPKI), publicKey (base64 DER SPKI), algorithm, createdAt and status. No private key material.' } } } },
  '/api/v1/shared/twins/{id}/datasets/context': { parameters: [twin], get: { summary: 'Read authorized historical bounds, measurement scope and export limits', security: session, responses: { '200': { description: 'serverTime, sessionExpiresAt, policyRevision, historyFrom, historyTo (exclusive; zero is unlimited), allMeasurements, measurements, maxRangeMs, maxArchiveBytes, ttlMs' }, ...errors } } },
  '/api/v1/shared/twins/{id}/history/query': { parameters: [twin], post: { summary: 'Query filtered retained samples using history scope 2; no ZIP is created', security: session, requestBody: json({ type: 'object', additionalProperties: false, required: ['fromTimestamp', 'toTimestamp'], properties: { measurements, fromTimestamp: { type: 'integer', minimum: 0 }, toTimestamp: { type: 'integer', minimum: 0 } } }), responses: { '200': { description: 'Samples, exact selection and current policy revision. Maximum 31 days within the granted history interval; timestamps in UTC milliseconds, query endpoints inclusive.' }, '409': { description: 'Source cannot be decrypted or filtered' }, ...errors } } },
  '/api/v1/shared/twins/{id}/location/latest': { parameters: [twin], get: { summary: 'Read latest structured position with location scope 8', security: session, responses: { '200': { description: 'Twin ID and position, or null if unavailable' }, ...errors } } },
  '/api/v1/shared/twins/{id}/realtime/latest': { parameters: [twin], get: { summary: 'Read telemetry filtered by realtime scope 1 and exact measure keys', security: session, responses: { '200': { description: 'Filtered payload; location omitted unless scope 8 is granted' }, '409': { description: 'Source cannot be decrypted or filtered' }, ...errors } } },
  '/api/v1/shared/twins/{id}/realtime/stream': { parameters: [twin], get: { summary: 'SSE with scope and revision checks on every sample and heartbeat', security: session, responses: { '200': { description: 'telemetry events; revoked event closes the stream on loss of access', content: { 'text/event-stream': { schema: { type: 'string' } } } }, ...errors } } },

  '/api/v1/twins/{id}/data-access': {
    parameters: [twin, { name: 'x-objectid-caller-did', in: 'header', required: true, schema: { type: 'string' } }],
    get: { summary: 'Owner: read canonical on-chain policy or the legacy activation draft', security: [{ ApiKey: [] }, { Bearer: [] }], responses: { '200': { description: 'Policy revision, mode, publicScopes, readers with scope bitmask, time bounds and exact measurement keys; legacy Twins return the previous flags' }, ...errors } },
    put: { summary: 'Legacy v1 only: set off-chain permissions; v2 requires an owner-signed Move transaction', security: [{ ApiKey: [] }, { Bearer: [] }], requestBody: json({ type: 'object', required: ['mode', 'visibility', 'liveLocationVisibility', 'allowedDids', 'revision'], properties: { mode: { enum: ['private', 'restricted', 'public'] }, visibility: { enum: ['private', 'public'] }, liveLocationVisibility: { enum: ['private', 'public'] }, allowedDids: didList, storageDids: { ...didList, description: 'Subset of allowedDids explicitly granted historical access. Omission preserves flags for remaining DIDs of the same owner.' }, revision: { type: 'string', nullable: true } } }), responses: { '200': { description: 'Policy updated; earlier export requests invalidated' }, '409': { description: 'Policy revision changed, or Twin uses owner-signed on-chain permissions' }, '422': { description: 'Invalid policy' }, ...errors } },
  },
  '/api/v1/shared/twins/{id}/challenge': { parameters: [twin], post: { summary: 'Request a DID-controller personal-message challenge', security: [], requestBody: json({ type: 'object', required: ['did'], properties: { did: { type: 'string' } } }), responses: { '200': { description: 'Challenge ID, exact message to sign and expiry' }, ...errors } } },
  '/api/v1/shared/twins/{id}/verify': { parameters: [twin], post: { summary: 'Verify DID signature and issue Twin-scoped reader session', security: [], requestBody: json({ type: 'object', required: ['did', 'challengeId', 'signature'], properties: { did: { type: 'string' }, challengeId: { type: 'string' }, signature: { type: 'string' } } }), responses: { '200': { description: 'Opaque bearer token and expiry. Use token in Authorization header only.' }, ...errors } } },
  '/api/v1/shared/twins/{id}/dashboard': { parameters: [twin], get: { summary: 'Restricted Twin identity and current reader permissions', security: session, responses: { '200': { description: 'Sanitized identity and permissions.realtime/history/export/location/evidence' }, ...errors } } },
  '/api/v1/shared/twins/{id}/datasets': { parameters: [twin], post: {
    summary: 'Prepare an ephemeral ZIP of retained telemetry (export scope 4 required, which also requires history scope 2)', security: session,
    requestBody: json({ type: 'object', additionalProperties: false, required: ['fromTimestamp', 'toTimestamp'], properties: { measurements, fromTimestamp: { type: 'integer', format: 'int64', minimum: 0, description: 'Inclusive observation time, Unix milliseconds' }, toTimestamp: { type: 'integer', format: 'int64', minimum: 0, description: 'Inclusive observation time, no future dates, at most 31 days after fromTimestamp' } } }),
    responses: { '202': { description: 'Preparing: requestId, statusUrl, expiresAt. Poll statusUrl every 2 seconds.' }, '422': { description: 'Invalid selection' }, ...errors },
  } },
  '/api/v1/shared/twins/{id}/datasets/{requestId}': { parameters: [twin, job],
    get: { summary: 'Read status using the original DID session', security: session, responses: { '200': { description: 'preparing/ready/failed; ready includes downloadUrl, sha256 and sampleCount; failed includes safe error' }, ...errors } },
    delete: { summary: 'Cancel and discard a temporary dataset', security: session, responses: { '204': { description: 'Discarded' }, ...errors } },
  },
  '/api/v1/shared/twins/{id}/datasets/{requestId}/download': { parameters: [twin, job], get: { summary: 'Download ZIP using original DID session; rechecks on-chain export scope, revision and owner', security: session, responses: { '200': { description: 'Filtered CSV, JSON and hash manifest; no new on-chain attestation. v2 encrypted sources are decrypted internally when the source key is configured, otherwise denied', headers: { 'X-Dataset-SHA256': { schema: { type: 'string' } } }, content: { 'application/zip': { schema: { type: 'string', format: 'binary' } } } }, '409': { description: 'Dataset not ready' }, ...errors } } },
};
